export const FONTS = [
    { name: 'Arial', type: 'O' },
    { name: 'Calibri', type: 'O' },
    { name: 'Times New Roman', type: 'O' },
    { name: 'Courier New', type: 'O' },
    { name: 'Segoe UI', type: 'O' },
    { name: 'Tahoma', type: 'O' },
    { name: 'Verdana', type: 'O' },
    { name: 'Georgia', type: 'O' },
    { name: 'Impact', type: 'O' },
    { name: 'Trebuchet MS', type: 'O' },
    { name: 'Century Gothic', type: 'O' },
    { name: 'Comic Sans MS', type: 'O' },
    { name: 'Rupee Forbidan', type: 'O' },
    { name: 'Agency FB', type: 'T' },
    { name: 'Algerian', type: 'T' },
    { name: 'Baskerville Old Face', type: 'T' },
    { name: 'Bauhaus 93', type: 'T' },
    { name: 'Bell MT', type: 'T' },
    { name: 'Bernard MT Condensed', type: 'T' },
    { name: 'Blackadder ITC', type: 'T' },
    { name: 'Bodoni MT', type: 'T' },
    { name: 'Bookman Old Style', type: 'T' },
    { name: 'Bradley Hand ITC', type: 'T' },
    { name: 'Broadway', type: 'T' },
    { name: 'Brush Script MT', type: 'T' },
    { name: 'Castellar', type: 'T' },
    { name: 'Centaur', type: 'T' },
    { name: 'Chiller', type: 'T' },
    { name: 'Cooper Black', type: 'T' },
    { name: 'Copperplate Gothic', type: 'T' },
    { name: 'Edwardian Script ITC', type: 'T' },
    { name: 'Elephant', type: 'T' },
    { name: 'Engravers MT', type: 'T' },
    { name: 'Felix Titling', type: 'T' },
    { name: 'Forte', type: 'T' },
    { name: 'Franklin Gothic', type: 'T' },
    { name: 'Garamond', type: 'T' },
    { name: 'Gigi', type: 'T' },
    { name: 'Gill Sans MT', type: 'T' },
    { name: 'Goudy Old Style', type: 'T' },
    { name: 'Harrington', type: 'T' },
    { name: 'Informal Roman', type: 'T' },
    { name: 'Jokerman', type: 'T' },
    { name: 'Lucida Calligraphy', type: 'T' },
    { name: 'Magneto', type: 'T' },
    { name: 'Mistral', type: 'T' },
    { name: 'Old English Text MT', type: 'T' },
    { name: 'Papyrus', type: 'T' },
    { name: 'Playbill', type: 'T' },
    { name: 'Showcard Gothic', type: 'T' },
    { name: 'Stencil', type: 'T' },
    { name: 'Viner Hand ITC', type: 'T' },
    { name: 'Vivaldi', type: 'T' },
    { name: 'Wide Latin', type: 'T' },
    { name: '@HP Simplified Hans', type: 'O', sub: 'Simplified Chinese', sample: '經HP簡' },
    { name: '@Malgun Gothic', type: 'O', sub: 'Korean', sample: '맑은 고딕' },
    { name: '@Meiryo', type: 'O', sub: 'Japanese', sample: 'メイリオ' },
    { name: '@Yu Gothic', type: 'O', sub: 'Japanese', sample: '游ゴシック' },
];

export const FONT_STYLES = ['Regular', 'Italic', 'Bold', 'Bold Italic'];
export const POINT_SIZES = [6, 7, 8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72];
